apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: default
data:
  01-pihole.conf: |-
    addn-hosts=/etc/pihole/local.list
    addn-hosts=/etc/pihole/custom.list

    localise-queries
    no-resolv

    cache-size=10000

    log-queries
    log-facility=/var/log/pihole.log
    local-ttl=2

    log-async
    server=8.8.8.8
    server=8.8.4.4
    interface=eth0
    server=/use-application-dns.net/
  02-custom.conf: |-
    address=/lab.javydekoning.com/192.168.1.9
    address=/hass.lab.javydekoning.com/192.168.1.200
    address=/pihole.lab.javydekoning.com/10.96.0.2
    address=/router.lab.javydekoning.com/192.168.1.1
---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: default
spec:
  selector:
    app: pihole
  type: ClusterIP
  clusterIP: 10.96.0.2
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: default
  labels:
    app: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pihole
    spec:
      initContainers:
        - name: clone
          image: alpine:latest
          command: ["/bin/ash"]
          args:
            - -c
            - >-
              apk add git --no-cache &&
              git clone https://github.com/javydekoning/homelab-pihole-k8s.git &&
              mv homelab-pihole-k8s/etc-dnsmasq.d/*.conf /dnsmasq/
          volumeMounts:
            - name: etc-dnsmasq
              mountPath: /dnsmasq
      containers:
        - name: pihole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: VIRTUAL_HOST
              value: pihole.lab.javydekoning.com
            - name: WEBPASSWORD
              value: NotMyPassword
          ports:
            - containerPort: 80 #Admin interface
            - containerPort: 53 #DNS
          volumeMounts:
            - name: etc-dnsmasq
              mountPath: /etc/dnsmasq.d/
            - name: etc-pihole
              mountPath: /etc/pihole/
      volumes:
        - name: etc-pihole
          emptyDir: {}
        - name: etc-dnsmasq
          emptyDir: {}
      restartPolicy: Always
      dnsConfig:
        nameservers:
          - 1.1.1.1
