apiVersion: v1
kind: Secret
metadata:
  name: plex-claim-token
  namespace: default
type: Opaque
data:
  token: ${API_TOKEN_OPAQUE}
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
spec:
  selector:
    app: plex
  type: ClusterIP
  clusterIP: 10.96.0.4
  ports:
    - name: http
      port: 80
      targetPort: 32400
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: default
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      app: plex
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plex
    spec:
      initContainers:
        - name: download-plex-plugins
          image: mcr.microsoft.com/powershell:preview-alpine-3.12
          securityContext:
            runAsUser: 911
            runAsGroup: 911
          command: ["/opt/microsoft/powershell/7-preview/pwsh"]
          args:
            - -Command
            - |-
              & {
                $VerbosePreference = 'Continue'
                $a = iwr https://github.com/pannal/Sub-Zero.bundle/releases/latest -UseBasicParsing
                $link = $a.links | ? href -match '/pannal/Sub-Zero.bundle/releases/download/.*Sub-Zero.bundle.*.zip'
                iwr ('https://github.com' + $link.href) -OutFile /tmp/SubZero.zip
                Expand-Archive /tmp/SubZero.zip '/config/plex/Library/Application Support/Plex Media Server/Plug-ins/' -f
                Write-host 'Sub-Zero version:'
                grep '^Version' '/config/plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Info.plist'
              }
          volumeMounts:
            - name: downloads
              mountPath: /config
              subPath: config
      containers:
        - name: plex
          image: linuxserver/plex
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
              ephemeral-storage: "2Gi"
            limits:
              memory: "16Gi"
              cpu: "2"
              ephemeral-storage: "4Gi"
          ports:
            - containerPort: 32400
              name: pms
          env:
            # Secrets
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-claim-token
                  key: token
            - name: TZ
              value: Europe/Amsterdam
            - name: PUID
              value: "911"
            - name: PGID
              value: "911"
            - name: VERSION
              value: docker
          volumeMounts:
            - name: downloads
              mountPath: /movies
              subPath: movies
            - name: downloads
              mountPath: /config
              subPath: config/plex
            - name: downloads
              mountPath: /tv
              subPath: tv
            - name: downloads
              mountPath: /education
              subPath: education
      volumes:
        - name: downloads
          hostPath:
            path: /downloads
            type: DirectoryOrCreate
